### PR TITLE
tons of bugfixes and tweaks

### LINKED ISSUE #22: ignore and unignore

### LINKED ISSUE #61: Why require the user to cut and paste or type a SHA?
https://github.com/ropenscilabs/ozrepro/blob/0d1b9b3913e9425071a337573149032d6e1addad/R/go_to.R#L11

To check out a commit that was n commits ago you can just use  git checkout branch-name@{n}

That way the user only needs to specify how far they wish to go back, and doesn’t have to fuss with SHAs at all. Or am I overlooking something that makes the need to specify a SHA essential?

I think the same may apply to the revert() function? Much better if the user can just specify an integer index of how far back the wish to go.

### PR DESCRIPTION
**Pull request by goldingn**
- removed dependencies on `githug`, `tibble`, `statquotes` and `checkmate`
 - implemented `scrub()`
 - implemented `ignore()` and `unignore()` (closes #22)
 - hid shas from users, they can now directly `go_to()`, and `retrieve()` records using integers (closes #61)
  - bunch 'o' bugfixes
 - made `print.timeline()` more minimal, and handle timelines when checking out past commits:
```
   (1) initial commit
    |  2017-10-29 13:27
    |
   (2) set up project structure
    |  2017-10-29 13:27
    |
   (3) added stuff to readme
       2017-10-29 13:27
     
   ...plus 12 future records (15 in total)
```

### CODE REVIEW

**Comment by goldingn** [comment]
@timchurches 
It looks like `notifier` won't install on travis, so I've switched back to using `message()` to get this to pass. 

I see gabor's build is failing for a different reason, so perhaps it's possible to get it working.

We could add `notifier` back in if we get this working, though it would stop us from being able to send this to CRAN (we don't depend on `githug` anymore, which was the other hurdle).

**Comment by goldingn** [comment]
OK, some final tweaks for this PR - putting a nice demo on the readme, and smoothing out the API to `changes()`

**Comment by dfalster** [comment]
Wow @goldingn !

**Comment by goldingn** [comment]
procrastination FTW :/

**Comment by smwindecker** [comment]
Nice! I was tweaking timeline() myself today to add the parameter options to allow you to display subset (by record number, date, message contents). Will this be compatible with the changes?

**Comment by goldingn** [comment]
Oh, that's a great idea!
Yeah it should be - just a matter of subsetting the dataframe (formerly a tibble, same difference) with an index, right?

**Comment by timchurches** [comment]
Just a note on etiquette: apart from trivial changes such as fixing typos, is it poor form to modify or refactor code written by someone else, and which has been submitted as a pull request for merging with master, and then charge ahead and merge the modified code with master without first consulting with the person who wrote the original pull-request code. By all means create an improved version of the pull-request code in a branch, but then ask the original author of that code "What do you think?" before merging it with master. Failure to observe that etiquette results in contributors rapidly losing interest, when they see that anything they do is second-guessed, without consultation. If there is a deadline, then eliding the consultation step is OK, but in this case, there is now absolutely no rush, afaik.

**Comment by goldingn** [comment]
I'm sorry Tim. I can see how bullish I came across and how frustrating that must have been.

FWIW I hadn't realised your PR would be automatically merged and closed when I merged mine. I was hoping just to get master it to pass the checks, and leave your PR open without leaving you a massive merge conflict to deal with.

I really appreciate the work you put into the reminders and would be keen to see the desktop notifications implemented!

Yesterday was somewhat a deadline for me as it was the last day for some months that I'll be able to spend any real time on this, so wanted to get it all in a working state for others to build on. But I could have handled this better. I'll try to be more conscientious in the future.

**Comment by timchurches** [comment]
No worries, and I don't think anyone is upset. The reminder function in stow is just a geegaw, in any case, although the _later_ package that it uses is really useful, although it needs more exploration, because it doesn't work as I expected it to from its fairly minimal documentation: it seems to behave more like a cronjob than an _at_ command, at least on macOS.

**Pull request merged**
